/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIObject */

#ifndef _Included_TestJNIObject
#define _Included_TestJNIObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIObject
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIObject_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
